config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  resources :users, except: [:new, :edit]
  resources :songs, except: [:new, :edit]
  resources :tabs_sets, except: [:new, :edit]
  resources :lyrics_sets, except: [:new, :edit]
  resources :password_resets, only: [:create, :edit]

  post 'reset_password/:id', to: 'password_resets#update', as: :reset_password

  get 'get_top_songs', to: 'songs#get_top_songs'
  get 'get_new_songs', to: 'songs#get_new_songs'
  get 'get_fresh_chords', to: 'tabs_sets#get_fresh_chords'
  get 'get_soundwave_url', to: 'songs#get_soundwave_url'

  get 'get_most_liked_tabs_set', to: 'tabs_sets#get_most_liked_tabs_set'
  get 'get_most_liked_lyrics_set', to: 'lyrics_sets#get_most_liked_lyrics_set'

  get 'get_tabs_sets', to: 'tabs_sets#get_tabs_sets'
  get 'get_lyrics_sets', to: 'lyrics_sets#get_lyrics_sets'
  get 'attempt_login', to: 'users#attempt_login'
  get 'validate_email', to: 'users#validate_email'

  resources :tabs_sets do
  member do
    put "like", to: "tabs_sets#upvote"
    put "dislike", to: "tabs_sets#downvote"
    put "change_visibility", to: "tabs_sets#change_visibility"
    end
  end

  resources :lyrics_sets do
  member do
    put "like", to: "lyrics_sets#upvote"
    put "dislike", to: "lyrics_sets#downvote"
    put "change_visibility", to: "lyrics_sets#change_visibility"
    end
  end

  resources :users do
  member do
    get "favorite_songs", to: "users#favorite_songs"
    put "favorite_a_song", to: "users#favorite_a_song"
    end
  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < WebBaseController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user
      user.send_password_reset
      render json: { message: "Email sent with password reset instructions"}
    else
      render json: { message: "Cannot find this user with email #{params[:email]}"}
    end
  end

  def edit
    @user = User.where(password_reset_token: params[:token]).first
  end

  def update
    @user = User.where(password_reset_token: params[:id]).first!
    if @user.password_reset_sent_at < 2.hours.ago
      @message = "This link has expired."
    elsif @user.update_password(update_params)
      @message = "Your password has been reset."
    end
  end

  def update_params
    params.require(:user).permit(:password)
  end

end

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_for @user, :url => reset_password_path(params[:id]), :method => 'POST' do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/password_resets/update.html.erb
<h3><%= @message %></h3>